groups {
    NFX-SXE-DEFAULT {
        interfaces {
            "<sxe-*>" {
                mtu 9192;
                ether-options {
                    no-flow-control;
                }
            }
        }
    }
}

interfaces {
    apply-groups NFX-SXE-DEFAULT;
}
