---
- name: "Apply configuration to Juniper devices"
  hosts: all
  connection: juniper.device.pyez
  gather_facts: false
  tasks:
    - name: "Ensure facts are gathered from device"
      juniper.device.facts:
      register: device_output

    - name: "Ensure device model is set as fact"
      ansible.builtin.set_fact:
        device_model: "{{ device_output.ansible_facts.junos.model | lower }}"

    - name: "Ensure device family prefix is set as fact"
      ansible.builtin.set_fact:
        device_family: "{{ device_model | regex_search('^[a-zA-Z]+') | lower }}"

    - name: "Ensure base configuration is present"
      juniper.device.config:
        load: "replace"
        format: "text"
        # Change to file or template depending on if you're using a template or static config file
        template: "{{ playbook_dir }}/templates/base.conf.j2"
        comment: "Loaded base configuration with Ansible"
        vars:
          name_servers: "{{ system_name_servers }}"
          ntp_servers: "{{ system_ntp_servers }}"

    - name: "Check if device-family-specific base configuration file exists"
      ansible.builtin.stat:
        path: "{{ playbook_dir }}/templates/{{ device_family }}-base.conf.j2"
      register: device_family_configuration

    - name: "Ensure device-family-specific base configuration is present"
      juniper.device.config:
        load: "replace"
        format: "text"
        # Change to file or template depending on if you're using a template or static config file
        template: "{{ playbook_dir }}/templates/{{ device_family }}-base.conf.j2"
        comment: "Loaded device-specific base configuration with Ansible"
        vars:
          hugepage_count: "{{ system_hugepage_count }}"
      when: device_family_configuration.stat.exists

    - name: "Check if host-specific configuration file exists"
      ansible.builtin.stat:
        path: "{{ playbook_dir }}/files/{{ inventory_hostname }}.conf"
      register: host_configuration

    - name: "Ensure host-specific configuration is present"
      juniper.device.config:
        load: "replace"
        format: "text"
        # Change to file or template depending on if you're using a template or static config file
        src: "{{ playbook_dir }}/files/{{ inventory_hostname }}.conf"
        comment: "Loaded device-specific base configuration with Ansible"
      when: host_configuration.stat.exists

- name: "Ensure SRX firewalls are configured"
  ansible.builtin.import_playbook: configure_srx.yml
