---
- name: "Apply configuration to Juniper devices"
  hosts: all
  connection: juniper.device.pyez
  gather_facts: false
  tasks:
    - name: "Ensure facts are gathered from device"
      juniper.device.facts:
      register: device_output

    - name: "Ensure device model is set as fact"
      ansible.builtin.set_fact:
        device_model: "{{ device_output['ansible_facts']['junos']['model'] | lower }}"

    - name: "Ensure device family prefix is set as fact"
      ansible.builtin.set_fact:
        device_family: "{{ device_model | regex_search('^[a-zA-Z]+') | lower }}"

    - name: "Apply configuration statements that require a reboot"
      juniper.device.config:
        load: "merge"
        lines: "{{ junos_reboot_required }}"
        format: "set"
        comment: "Loaded configuration that required reboot with Ansible"
        timeout: 300
      when: junos_reboot_required is defined and junos_reboot_required | length > 0
      notify: "Reboot device"

    - name: "Ensure Junos OS configuration tiers are merged"
      ansible.builtin.set_fact:
        merged_junos_config: >-
          {{
            junos_config_base | default({})
            | combine(junos_config_group | default({}), recursive=True)
            | combine(junos_config_host | default({}), recursive=True, list_merge='replace')
          }}

    - name: "Ensure Junos OS configuration is applied with Ansible"
      juniper.device.config:
        load: "merge"
        format: "text"
        lines: "{{ merged_junos_config | iambryant.junos.to_junos }}"
        comment: "{{ commit_message | default('Automated deployment via Ansible') }}"
        timeout: 300

  handlers:
    - name: "Ensure device is rebooted"
      juniper.device.system:
        action: "reboot"
         # Needs to be set manually per host/group since 'juniper.device.facts' incorrectly reports vmhost: false when
         # tested on vmhost devices such as the NFX or QFX
         # You can choose to set this per-host in host_vars if the device uses a vmhost architecture, such as the
         # SRX1500 while not affecting non vmhost SRXes like an SRX340
        vmhost: "{{ juniper_vmhost | default(device_family in ['nfx', 'qfx']) }}"
      # Templating the vmhost parameter causes the module to lose proper connection-tracking state, throwing a
      # 'ConnectClosedError' prematurely even though the reboot succeeds. 'failed_when' is used here as a workaround
      failed_when: false
      listen: "Reboot device"

    - name: "Wait for device to come back online"
      ansible.builtin.wait_for:
        # Switch to 'ansible_host' if your hosts aren't in DNS
        host: "{{ inventory_hostname }}"
        port: 830
        timeout: 600
        delay: 60
      listen: "Reboot device"
